# Generated by Django 3.2.12 on 2023-11-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGurdata',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_surname', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=40, unique=True)),
                ('user_company', models.CharField(max_length=30)),
                ('user_company_role', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=200)),
                ('user_balance', models.IntegerField()),
                ('user_confirmed', models.IntegerField()),
                ('user_deleted', models.IntegerField()),
            ],
        ),
    ]
