# Generated by Django 3.2.12 on 2023-11-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergurdata',
            table='user_gurdata',
        ),
    ]
