# Generated by Django 3.2.12 on 2023-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0002_alter_usergurdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGurdata',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_name', models.CharField(max_length=40)),
                ('data_path', models.CharField(max_length=100)),
                ('data_demo_path', models.CharField(max_length=100)),
                ('data_download_count', models.IntegerField()),
            ],
            options={
                'db_table': 'data_gurdata',
            },
        ),
    ]
