# Generated by Django 3.2.12 on 2023-11-09 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0003_datagurdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDownloadGurdata',
            fields=[
                ('download_id', models.AutoField(primary_key=True, serialize=False)),
                ('download_datatime', models.DateTimeField()),
                ('download_time_minute', models.IntegerField()),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gurdataApp.datagurdata')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gurdataApp.usergurdata')),
            ],
            options={
                'db_table': 'data_download_gurdata',
            },
        ),
    ]
