# Generated by Django 3.2.12 on 2023-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0004_datadownloadgurdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGurdata',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contact_gurdata',
            },
        ),
    ]
