# Generated by Django 3.2.12 on 2023-11-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0005_contactgurdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_notifications', models.IntegerField(default=1)),
                ('file_manager_notifications', models.IntegerField(default=0)),
                ('mail_notifications', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gurdataApp.usergurdata')),
            ],
            options={
                'db_table': 'system_notification',
            },
        ),
    ]
