# Generated by Django 3.2.12 on 2023-12-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0008_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCategoryGurdata',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_description', models.TextField()),
                ('category_image', models.ImageField(upload_to='category_images/')),
            ],
        ),
    ]
