# Generated by Django 3.2.12 on 2023-12-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0009_datacategorygurdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagurdata',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gurdataApp.datacategorygurdata'),
        ),
        migrations.AddField(
            model_name='datagurdata',
            name='data_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datagurdata',
            name='data_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
