# Generated by Django 3.2.12 on 2023-12-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0011_auto_20231204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacategorygurdata',
            name='category_image',
            field=models.ImageField(upload_to='./gurdata/gurdataApp/static/category_images/'),
        ),
    ]
