# Generated by Django 4.2.7 on 2023-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0013_alter_datacategorygurdata_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacategorygurdata',
            name='category_image',
            field=models.ImageField(upload_to='./gurdataApp/static/category_images'),
        ),
    ]
