# Generated by Django 3.2.12 on 2023-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0014_alter_datacategorygurdata_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergurdata',
            name='user_data',
            field=models.ManyToManyField(blank=True, related_name='users', to='gurdataApp.DataGurdata'),
        ),
    ]
