# Generated by Django 3.2.12 on 2024-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0015_usergurdata_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacategorygurdata',
            name='genre',
            field=models.CharField(choices=[('R', 'Novel'), ('SF', 'Science Fiction'), ('M', 'Mystery'), ('H', 'History'), ('D', 'Drama')], default='R', max_length=2),
        ),
    ]
