# Generated by Django 3.2.12 on 2024-01-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0016_datacategorygurdata_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacategorygurdata',
            old_name='genre',
            new_name='category_svg',
        ),
    ]
