# Generated by Django 3.2.12 on 2024-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurdataApp', '0022_alter_datacategorygurdata_category_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadownloadgurdata',
            name='download_time_minute',
        ),
        migrations.AddField(
            model_name='datagurdata',
            name='data_time_minute',
            field=models.IntegerField(default=5000),
        ),
    ]
